"""add external_url and source to news_articles

Revision ID: 260c1568ba8e
Revises: a7cee058829d
Create Date: 2026-04-14 17:19:05.027028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260c1568ba8e'
down_revision = 'a7cee058829d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('external_url')

    # ### end Alembic commands ###
